Implemented create Wallet endpoint
Dwit-Tech/wallet-service pull request #2
Opened 2023-07-20 10:11 UTC by giftedGeorge

2023-08-01 08:27 UTC, M-Jhay approved these changes
Looks good

2023-08-02 11:07 UTC, johnny2565 approved these changes
Looks good to me, I approve this PR for merging

2023-08-06 23:00 UTC, dabensymon requested changes
Reach out to @M-Jhay, you need to include a Name and email address in this payload. Also, this should be a DTO too.

2023-08-06 23:02 UTC, dabensymon approved these changes

2023-08-06 23:03 UTC, merged